# Churn Modelling Problem
In this part, you will be solving a data analytics challenge for a bank. You will be given a dataset with a large sample of the bank’s customers. To make this dataset, the bank gathered information such as customer id, credit score, gender, age, tenure, balance, if the customer is active, has a credit card, etc. During 6 months, the bank observed if these customers left or stayed in the bank.

Your goal is to make an Artificial Neural Network that can predict, based on geo-demographical and transactional information given above, if any individual customer will leave the bank or stay (customer churn). Besides, you are asked to rank all the customers of the bank, based on their probability of leaving. To do that, you will need to use the right Deep Learning model, one that is based on a probabilistic approach.

If you succeed in this project, you will create significant added value to the bank. By applying your Deep Learning model the bank may significantly reduce customer churn.

In [2]:
!pip install tensorflow

In [3]:
!pip install keras

In [4]:
#import libaraeies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
#import churn modelling daatset
data=pd.read_csv("Churn_Modelling.csv")
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

# EDA

In [6]:
data.shape

(10000, 14)

In [7]:
data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [8]:
data.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [9]:
data.duplicated().sum()

0

## divide the dataset into inputs and output 

In [10]:
x=data.iloc[:,3:13].values #inputs
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [11]:
#output
y=data.iloc[:, 13].values
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

## Encoding the Categorical data
### In this step, we Encode our categorical data. If we see our dataset then Geography & Gender attribute is in Text and we Encode these two attributes in this part use the LabelEncoder and OneHOTEncoder from the Sklearn.processing library.

In [12]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_x1=LabelEncoder()
x[:,1]=labelencoder_x1.fit_transform(x[:,1])
labelencoder_x2=LabelEncoder()
x[:,2]=labelencoder_x2.fit_transform(x[:,2])

# now we aree applying one hot encoding on x data
onehotencoder=OneHotEncoder()
x=onehotencoder.fit_transform(x).toarray()
x=x[:, 1:]


In [13]:
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [14]:
x.shape

(10000, 16934)

# data splitting

In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.2, random_state=0)

In [16]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [17]:
x_train.shape

(8000, 16934)

# model building

In [18]:
# ANN Libraries
import keras
from keras.models import Sequential
from keras.layers import Dense

In [33]:
#intilize our ANN MOdel
classifier=Sequential()

In [34]:
#Adding the input layer and first hidden layer
classifier.add(Dense(6, kernel_initializer='uniform', input_shape=(x_train.shape[1],), activation='relu', input_dim=11))

In [35]:
#Adding the second hidden layer
classifier.add(Dense(units=6, kernel_initializer='uniform', activation='relu'))

In [36]:
#Adding the third hidden layer
classifier.add(Dense(units=8, kernel_initializer='uniform', activation='relu'))

In [37]:
#adding output layer
classifier.add(Dense(units=1, kernel_initializer='normal', activation='sigmoid'))

In [38]:
#compliling the ANN
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [39]:
#Fitting the ANN
classifier.fit(x_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
800/800 [==============================] - 8s 7ms/step - loss: 0.5201 - accuracy: 0.7950
Epoch 2/100
800/800 [==============================] - 5s 7ms/step - loss: 0.4451 - accuracy: 0.7960
Epoch 3/100
800/800 [==============================] - 5s 7ms/step - loss: 0.3575 - accuracy: 0.7960
Epoch 4/100
800/800 [==============================] - 5s 7ms/step - loss: 0.2620 - accuracy: 0.8390
Epoch 5/100
800/800 [==============================] - 6s 7ms/step - loss: 0.2186 - accuracy: 0.8813
Epoch 6/100
800/800 [==============================] - 6s 7ms/step - loss: 0.2028 - accuracy: 0.8935
Epoch 7/100
800/800 [==============================] - 5s 7ms/step - loss: 0.1950 - accuracy: 0.8994
Epoch 8/100
800/800 [==============================] - 6s 7ms/step - loss: 0.1855 - accuracy: 0.9068
Epoch 9/100
800/800 [==============================] - 5s 7ms/step - loss: 0.1825 - accuracy: 0.9091
Epoch 10/100
800/800 [==============================] - 5s 7ms/step - loss: 0.1816 - accura

In [47]:
#predict the test set result
y_pred=classifier.predict(x_test)
y_pred=y_pred>0.5
y_pred

63/63 [==============================] - 0s 7ms/step


array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [48]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
print("the confusion matrix is:", confusion_matrix(y_test, y_pred),"\n", "the accuracy is:", accuracy_score(y_test, y_pred),
     "\n", "classification report is :", classification_report(y_test, y_pred))

the confusion matrix is: [[1289  306]
 [ 156  249]] 
 the accuracy is: 0.769 
 classification report is :               precision    recall  f1-score   support

           0       0.89      0.81      0.85      1595
           1       0.45      0.61      0.52       405

    accuracy                           0.77      2000
   macro avg       0.67      0.71      0.68      2000
weighted avg       0.80      0.77      0.78      2000

